### ISSUE TITLE
Extend DetectionSuite to include Python based detection networks

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/dl-DetectionSuite#18]
as those generated from TensorFlow and Keras. Their code should be run from the C++ DetectionSuite code. 

A Python based model should be trained on its corresponding neural networks middleware, but its inference step should be called from DetectionSuite, providing it an image as input and reading its output bounding boxes from DetectionSuite too.

**Comment by vinay0410** [comment]
I would like to add that list of bounding boxes, detection scores, etc are returned in the form of numpy.ndarray by tensorflow, so inorder to read that in C++, we might have to use [numpy c api](https://docs.scipy.org/doc/numpy-1.13.0/reference/c-api.html) also which has ```ArrayObject`` available for this purpose.

**Comment by chanfr** [comment]
Hi @vinay0410 ,
the video looks awesome, great job!

I'm having some troubles to make your code work, I'm getting the following error when trying to use the tensorflow backend:

------------------------------------------------------------------
returned tensorflow
in tensorflow constructor
InterPreter Initailized
Loading Detection Graph
Traceback (most recent call last):
  File "/home/frivas/devel/gsoc2018/dl-DetectionSuite/DeepLearningSuite/DeepLearningSuiteLib/python_modules/tensorflow_detect.py", line 2, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/framework_lib.py", line 76, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/eager/context.py", line 28, in <module>
    from tensorflow.python.platform import app
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 23, in <module>
    from tensorflow.python.platform import flags
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 26, in <module>
    _global_parser = _argparse.ArgumentParser()
  File "/usr/lib/python2.7/argparse.py", line 1586, in __init__
    prog = _os.path.basename(_sys.argv[0])
AttributeError: 'module' object has no attribute 'argv'
Cannot find function "tensorflow_detect"
Detection Graph Loaded

my config:
echo $PYTHONPATH
/home/frivas/devel/dl-DetectionSuite/DeepLearningSuite/DeepLearningSuiteLib/python_modules/

Anything else that i'm missing?

I have some questions:
1. Which python version should I use?
2. I have to specify something in the "Net Configuration" box? or just a foo file?


cheers,

**Comment by vinay0410** [comment]
Thanks for replying!
I have tested this in python 2.7.

Though, the error seems to be tensorflow import error. Which version of tensorflow are you using?
I have tested it in 1.5.0.
Also could please trying import tensorflow in terminal by typing ```python``` and importing tensorflow.
See if this error occurs again. 
Also, your ```PYTHONPATH``` is set to a different location as compared to the directory printed in stack trace here 
```
Traceback (most recent call last):
File "/home/frivas/devel/gsoc2018/dl-DetectionSuite/DeepLearningSuite/DeepLearningSuiteLib/python_modules/tensorflow_detect.py", line 2, in 
```
Although, that shouldn't cause a problem , but changing that would certainly help in future.

Also, it is necessary to specify something in the Net Configuration, and that can be a foo file since it will not be used.

**Comment by vinay0410** [comment]
Hi @chanfr,
I have added a commit which will probably fix your issue know, which regarding importing tensorflow.
It seems as if tensorflow requires ```sys.argv```, when being imported and while it is being called from C++, ```sys.argv``` is generally not set.
So, I have added an empty sys.argv.
Please try again and see if it fixes your issue.
I have tested it again on my computer and works great even after this minor alteration.
Also, do add your ```PYTHONPATH``` in the python_modules of the updated repository.
